source 'https://github.com/CocoaPods/Specs.git'
platform :ios, '8.0'
link_with 'PhotixFilter'
pod 'GPUImage'
pod 'MGInstagram'
pod 'MBProgressHUD'
pod 'Google-Mobile-Ads-SDK', '~> 7.0'
pod 'GMImagePicker', '~> 0.0.2'
